title:            Humans and Agents Lab
description:      "Humans and Agents Lab at Western University."
url: "https://atrisha.github.io/uwoagents"

urlimg: '/images/'
header-img: images/homepage.jpg

# Comments powered by utteranc.es
utterances: "atrisha/atrisha.github.io"

reading_time: true
word_count: true
words_per_minute: 100
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Main author of the website
# See > authors.yml
author: atrisha

# Owner/author information
owner:
  name:           Atrisha Sarkar
  avatar:         avatar.jpg
  bio:            "Dr. Atrisha Sarkar is an assistant professor in the Department of Electrical and Computer Engineering at Western University since 2025. 
  Before that, she was a postdoctoral fellow at University of Toronto. She received her PhD in 2022 from University of Waterloo in Computer Science.
  She has also spent eight years in the industry prior to graduate school."
  email: atrisha.sarkar@uwo.ca
  # Social networking links used in footer. Update and remove as you like.
  twitter: 
  facebook:
  github: atrisha
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Toronto
future: true
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:title  #/:categories/:title/

# Amount of post to show on home page
paginate: 5
paginate_path: "blog/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    formatter: Rouge::Formatters::HTMLLineTable
    # line_numbers: true # this will make inline code broken
    # line_table: true
    # css_class: ''
    span:
      line_numbers: false
    block:
      line_numbers: true
      output: markdown
    default_lang: text
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
